#APP ENV
app:
  env: "dev"
  sysname: "go-api-frame"
  port: 80
  runtime: "dev"

#Redis
redis:
  address: "127.0.0.1:6379"
  prefix: "msp"
  expire: 604800
  connect-timeout: 6000
  read-timeout: 6000
  write-timeout: 6000
  pool-max-idel: 5000
  pool-max-active: 20
  pool-min-active: 10
  pool-idle-timeout: 200000
  password: ""

#Mysql
mysql:
  dbname: "msp"
  pool:
    pool-min-cap: 10
    pool-ex-cap: 5
    pool-max-cap: 40
    pool-idle-timeout: 3600
    pool-wait-count: 1000
    pool-wai-timeout: 30
  write:
    address: "192.168.2.80:3306"
    port: 3306
    user: "root"
    password: "123456"

#RabbitMQ
rabbitmq:
  uri: "amqp://admin:admin@192.168.2.80:5672"
  vhost: "/"
  exchange: "msp.register.center"
  exchange-type: "direct"
  consumer-tag: "simple-consumer"
  lifetime: 0 #//秒

#日志
log:
  out-put: "redis"
  debug: true
  key: "msp_log"
  redis:
    host: "127.0.0.1:6379"
    port: 6379
  app:
    app-name: "go-api-frame"
    app-id: "appid"
    app-version: "1.0.0"
    app-key: "appkey"
    channel: "1"
    sub-org-key: "sub_org_key"
    language: "ch"

elastic:
  address: "https://es.logservice.cidata-sh.oneitfarm.com"
  username: "msp_log"
  password: "wbPqDCTa6mh68DBv"
  index: "msp_log$result_service_log"
  timeout: 8000 #单位 毫秒
  transport-max-idel: 250
  health-check-enabled: false
  health-check-timeout: 10 #单位 秒
  health-check-interval: 60 #单位 秒
  sniffer-enabled: false

code:
  0: "成功"
  1001: "成功"
  1002: "验证签名失败"
  1003: "服务器繁忙，请稍后再试"
  1004: "请求参数错误"
  1005: "用户未登录"
  1006: "记录不存在"
  1007: "记录已经存在"
  1008: "时序查询错误"
