{
 "title": "MSP 注册中心资源监控",
 "description": "MSP 注册中心资源监控",
 "tags": [ "msp" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "identification",
    "label": "identification",
    "query": "select identification from \"testdb\".\"autogen\".\"register_center_resource\""
   },
   {
    "name": "container_name",
    "label": "container_name",
    "query": "SELECT \"container_name\" FROM \"testdb\".\"autogen\".\"register_center_resource\"  GROUP BY \"/^$identification$/\""
   }
  ]
 },
 "panels": [
  { "title": "注册中心宿主机监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "注册中心宿主机使用内存",
   "type": "graph",
   "description": "注册中心宿主机使用内存",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean_host_memory",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "query": "SELECT mean(\"host_memory\") FROM \"autogen\".\"register_center_resource\" WHERE (\"agent\" = 'resource') AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "host_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  {
   "title": "注册中心宿主机已使用内存",
   "type": "graph",
   "description": "注册中心宿主机已使用内存",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "mean_host_memory_mb",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "select": [
      [
       { "params": [ "host_memory_MB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  { "title": "注册中心容器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "容器分配总内存",
   "type": "stat",
   "description": "容器分配总内存",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "last_container_memory",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "/^$identification$/" ], "type": "tag" },
      { "params": [ "/^$container_name$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "select": [
      [
       { "params": [ "memory_total_MB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  {
   "title": "容器CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean_cpu",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "/^$identification$/" ], "type": "tag" },
      { "params": [ "/^$container_name$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "query": "SELECT mean(\"cpu\") FROM \"autogen\".\"register_center_resource\" WHERE (\"agent\" = 'resource') AND $timeFilter GROUP BY time(5s), \"/^$identification$/\", \"/^$container_name$/\" fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  {
   "title": "容器内存使用率",
   "type": "graph",
   "description": "当前容器所占内存百分比",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "mean_memory",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "/^$identification$/" ], "type": "tag" },
      { "params": [ "/^$container_name$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "query": "SELECT mean(\"memory\") FROM \"autogen\".\"register_center_resource\" WHERE (\"agent\" = 'resource') AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  {
   "title": "容器内存使用量",
   "type": "graph",
   "description": "当前容器使用内存",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "mean_memory_mb",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" },
      { "params": [ "/^$identification$/" ], "type": "tag" },
      { "params": [ "/^$container_name$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "query": "SELECT mean(\"memory_MB\") FROM \"autogen\".\"register_center_resource\" WHERE (\"agent\" = 'resource') AND $timeFilter GROUP BY time(5s) fill(null)",
     "select": [
      [
       { "params": [ "memory_MB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  },
  {
   "title": "注册中心-监控Agent 内存消耗",
   "type": "graph",
   "description": "当前Agent所占内存",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "alias": "mean_agent_memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "/^$identification$/" ], "type": "tag" },
      { "params": [ "/^$container_name$/" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "register_center_resource",
     "query": "SELECT mean(\"agent_memory\") FROM \"msp_testdb\".\"register_center_resource\" WHERE (\"agent\" = 'resource') AND $timeFilter GROUP BY time(5s), \"/^$identification$/\", \"/^$container_name$/\" fill(null)",
     "select": [
      [
       { "params": [ "agent_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent", "operator": "=", "value": "resource" }
     ]
    }
   ]
  }
 ]
}