package pconst

const (
	//common
	CODE_ERROR_OK                  = 0
	CODE_COMMON_OK                 = 1001
	CODE_COMMON_ACCESS_FAIL        = 1002
	CODE_COMMON_SERVER_BUSY        = 1003
	CODE_COMMON_PARAMS_INCOMPLETE  = 1004
	CODE_COMMON_USER_NO_LOGIN      = 1005
	CODE_COMMON_DATA_NOT_EXIST     = 1006
	CODE_COMMON_DATA_ALREADY_EXIST = 1007
	CODE_VICTORIA_METRICS_ERR      = 1008
)

/*
注册中心相关
*/
const (
	STATIC_REGISTER_CENTER_TYPE  = 1
	DYNAMIC_REGISTER_CENTER_TYPE = 2
)
