// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/log_platform": {
            "put": {
                "description": "修改日志平台数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Edit LogPlatformData",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "主键ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务名称",
                        "name": "service_name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "服务appid",
                        "name": "appid",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "日志log_key",
                        "name": "log_key",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "流量开关，1开2关",
                        "name": "is_block",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "速率限制",
                        "name": "rate_limit",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            },
            "post": {
                "description": "新增日志平台数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Add LogPlatformData",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服务名称",
                        "name": "service_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务appid",
                        "name": "appid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日志log_key",
                        "name": "log_key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "流量开关，1开2关",
                        "name": "is_block",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "速率限制",
                        "name": "rate_limit",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            }
        },
        "/log_platform/count": {
            "get": {
                "description": "获取日志平台key的数量",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Get LogKeyCount",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "是否关闭流量，2关闭1开启",
                        "name": "is_block",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "速率限制，单位：次/s",
                        "name": "rate_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            }
        },
        "/log_platform/info/{id}": {
            "get": {
                "description": "获取日志平台某个服务详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Get LogPlatformDataInfo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务主键ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            }
        },
        "/log_platform/sidecar/log_key_list": {
            "get": {
                "description": "日志SideCar获取接入的log_key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Get LogPlatformDataList For SideCar",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            }
        },
        "/log_platform/{id}": {
            "delete": {
                "description": "删除日志平台某个服务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志平台"
                ],
                "summary": "Delete LogPlatformData",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务主键ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Res"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Res": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "go-api-frame API",
	Description: "This is go-api-frame api list.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
