basePath: /api/v1
definitions:
  controller.Res:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: This is go-api-frame api list.
  license: {}
  title: go-api-frame API
  version: 1.0.0
paths:
  /log_platform:
    post:
      description: 新增日志平台数据
      parameters:
      - description: 服务名称
        in: formData
        name: service_name
        required: true
        type: string
      - description: 服务appid
        in: formData
        name: appid
        required: true
        type: string
      - description: 日志log_key
        in: formData
        name: log_key
        required: true
        type: string
      - description: 流量开关，1开2关
        enum:
        - 1
        - 2
        in: formData
        name: is_block
        type: integer
      - description: 速率限制
        in: formData
        name: rate_limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Add LogPlatformData
      tags:
      - 日志平台
    put:
      description: 修改日志平台数据
      parameters:
      - description: 主键ID
        in: formData
        name: id
        required: true
        type: integer
      - description: 服务名称
        in: formData
        name: service_name
        type: string
      - description: 服务appid
        in: formData
        name: appid
        type: string
      - description: 日志log_key
        in: formData
        name: log_key
        type: string
      - description: 流量开关，1开2关
        enum:
        - 1
        - 2
        in: formData
        name: is_block
        type: integer
      - description: 速率限制
        in: formData
        name: rate_limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Edit LogPlatformData
      tags:
      - 日志平台
  /log_platform/{id}:
    delete:
      description: 删除日志平台某个服务
      parameters:
      - description: 服务主键ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Delete LogPlatformData
      tags:
      - 日志平台
  /log_platform/count:
    get:
      description: 获取日志平台key的数量
      parameters:
      - description: 是否关闭流量，2关闭1开启
        in: query
        name: is_block
        type: integer
      - description: 速率限制，单位：次/s
        in: query
        name: rate_limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Get LogKeyCount
      tags:
      - 日志平台
  /log_platform/info/{id}:
    get:
      description: 获取日志平台某个服务详情
      parameters:
      - description: 服务主键ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Get LogPlatformDataInfo
      tags:
      - 日志平台
  /log_platform/sidecar/log_key_list:
    get:
      description: 日志SideCar获取接入的log_key
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Res'
      summary: Get LogPlatformDataList For SideCar
      tags:
      - 日志平台
swagger: "2.0"
